services:
  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 

  local.postgres:
    image: postgres:latest # or latest
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432